version: '3.8'

services:
  web:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - ./uploads:/app/uploads
    environment:
      - FORWARDED_ALLOW_IPS=*
      - PROXY_HEADERS=1
    restart: unless-stopped
    
  # 可选：添加nginx反向代理来更好地处理真实IP
  nginx:
    image: nginx:alpine
    ports:
      - "88:88"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /mnt/server/host_message_files:/mnt/server/host_message_files
    depends_on:
      - web
    restart: unless-stopped 